[tool.poetry]
name = "stonks"
version = "0.1.0"
description = ""
authors = ["Lenon Marcel <lenon.marcel@gmail.com>"]

[tool.poetry.dependencies]
python = "3.11.5"
pandas = "^2.1.1"
xlwings = "^0.30.12"
pandera = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4"
black = "^23.9"
isort = "^5.12.0"
coverage = "^7.2"
mypy = "^1.6.1"
pandera = {extras = ["mypy"], version = "^0.17.0"}
vcrpy = "^5.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
no_sections = true
length_sort = true

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.pytest.ini_options]
addopts = "--capture=tee-sys --no-header --quiet --tb=short"

[tool.coverage.run]
branch = true
omit = ["tests/*"]
dynamic_context = "test_function"

[tool.coverage.html]
show_contexts = true

[tool.mypy]
strict = true
