[tool.poetry]
name = "stonks"
version = "0.1.0"
description = ""
authors = ["Lenon Marcel <lenon.marcel@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.3.5"
openpyxl = "^3.0.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^21.12b0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
no_sections = true
length_sort = true
