[tool.poetry]
name = "stonks"
version = "0.1.0"
description = ""
authors = ["Lenon Marcel <lenon.marcel@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.4.1"
openpyxl = "^3.0.9"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
black = "^22.1"
isort = "^5.10.1"
coverage = "^6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
no_sections = true
length_sort = true

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.pytest.ini_options]
addopts = "--capture=tee-sys --no-header --quiet --tb=short"

[tool.coverage.run]
branch = true
omit = ["tests/*"]
dynamic_context = "test_function"

[tool.coverage.html]
show_contexts = true
