name: CI
on:
  - push
env:
  POETRY_VERSION: 1.1.13
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: scripts/read-python-version.sh
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache Poetry
        uses: actions/cache@v2
        with:
          path: |
            ~/.local/share/pypoetry
            ~/.local/bin/poetry
          key: poetry-${{ runner.os }}-python-${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        run: scripts/install-poetry.sh
      - name: Cache virtual envs
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venvs-${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ hashFiles('poetry.lock') }}
      - run: poetry install
      - run: poetry run coverage run -m pytest
      - run: poetry run coverage html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: htmlcov/
