SHEET_NAMES = {
    "positions": "Posição",
    "trade_confirmations": "Notas de corretagem",
    "trades": "Negócios",
    "rights": "Subscrições",
    "splits": "Desdobramentos",
    "mergers": "Incorporações",
    "spin_offs": "Cisões",
    "stock_dividends": "Bonificações",
    "ptax": "PTAX",
    "us_trades": "US | Trades",
    "us_positions": "US | Positions",
    "us_dividends": "US | Dividends",
}

TABLE_COLUMNS = {
    "positions": {
        "symbol": "Código",
        "quantity": "Quantidade",
        "cost": "Custo Total",
        "cost_per_share": "PM",
    },
    "trade_confirmations": {
        "date": "Data",
        "broker": "Corretora",
        "sales": "Vendas",
        "purchases": "Compras",
        "traded_volume": "Vol. Negociado",
        "clearing_fees": "Taxa de Liq.",
        "trading_fees": "Emolumentos",
        "brokerage_fees": "Corretagem",
        "income_tax": "IR",
        "costs": "Custos",
        "amount": "Total",
    },
    "trades": {
        "date": "Data",
        "broker": "Corretora",
        "symbol": "Código",
        "type": "Tipo",
        "quantity": "Quantidade",
        "price": "Preço",
        "costs": "Custos",
        "amount": "Total",
    },
    "rights": {
        "date": "Data",
        "broker": "Corretora",
        "symbol": "Código",
        "description": "Descrição",
        "start": "Início",
        "end": "Fim",
        "settlement": "Liquidação",
        "shares": "Quantidade",
        "exercised": "Exercido",
        "price": "Preço",
        "amount": "Valor Total",
        "issue_date": "Emissão",
    },
    "splits": {"date": "Data", "symbol": "Código", "ratio": "Proporção"},
    "mergers": {"date": "Data", "symbol": "Código", "acquirer": "Compradora", "ratio": "Proporção"},
    "spin_offs": {
        "date": "Data",
        "symbol": "Código",
        "new_company": "Novo Código",
        "ratio": "Proporção",
        "cost_basis": "Percentual Custo",
    },
    "stock_dividends": {
        "date": "Data",
        "symbol": "Código",
        "quantity": "Quantidade",
        "cost": "Custo",
    },
    "ptax": {"date": "Data", "buying_rate": "Compra", "selling_rate": "Venda"},
    "us_trades": {
        "date": "Date",
        "symbol": "Symbol",
        "type": "Type",
        "quantity": "Quantity",
        "price": "Price",
        "commission": "Commission",
        "reg_fee": "Reg Fee",
        "costs": "Costs",
        "amount": "Amount",
        "ptax": "PTAX",
        "price_brl": "Price BRL",
        "amount_brl": "Amount BRL",
    },
    "us_positions": {
        "symbol": "Symbol",
        "quantity": "Quantity",
        "cost": "Cost",
        "cost_per_share": "Cost per share",
        "cost_brl": "Cost (R$)",
        "cost_per_share_brl": "Cost per share (R$)",
    },
    "us_dividends": {
        "date": "Date",
        "symbol": "Symbol",
        "amount": "Amount",
        "taxes": "Taxes",
        "total": "Total",
        "ptax": "PTAX",
        "amount_brl": "Amount (BRL)",
        "taxes_brl": "Taxes (BRL)",
        "total_brl": "Total (BRL)",
    },
}

TABLE_VALUES = {
    "trades": {"type": {"C": "buy", "V": "sell"}},
    "us_trades": {"type": {"B": "buy", "S": "sell"}},
}

TABLE_INDEXES = {
    "trade_confirmations": ["date", "broker"],
    "trades": ["date", "broker"],
    "rights": ["date", "broker"],
    "splits": ["date", "symbol"],
    "mergers": ["date", "symbol"],
    "spin_offs": ["date", "symbol"],
    "stock_dividends": ["date", "symbol"],
    "ptax": ["date"],
    "us_trades": ["date"],
    "us_dividends": ["date"],
}
